// colleges-list.js — searchable pool for Add School modal
window.COLLEGE_LIST = [
  // Ivy League
  {id:'harvard',name:'Harvard University',location:'Cambridge, MA',type:'Private · Ivy League'},
  {id:'yale',name:'Yale University',location:'New Haven, CT',type:'Private · Ivy League'},
  {id:'princeton',name:'Princeton University',location:'Princeton, NJ',type:'Private · Ivy League'},
  {id:'columbia',name:'Columbia University',location:'New York, NY',type:'Private · Ivy League'},
  {id:'penn',name:'University of Pennsylvania',location:'Philadelphia, PA',type:'Private · Ivy League'},
  {id:'brown',name:'Brown University',location:'Providence, RI',type:'Private · Ivy League'},
  {id:'dartmouth',name:'Dartmouth College',location:'Hanover, NH',type:'Private · Ivy League'},
  {id:'cornell',name:'Cornell University',location:'Ithaca, NY',type:'Private · Ivy League'},
  // Elite Private Research
  {id:'mit',name:'MIT',location:'Cambridge, MA',type:'Private Research'},
  {id:'stanford',name:'Stanford University',location:'Stanford, CA',type:'Private Research'},
  {id:'caltech',name:'Caltech',location:'Pasadena, CA',type:'Private Research'},
  {id:'chicago',name:'University of Chicago',location:'Chicago, IL',type:'Private Research'},
  {id:'duke',name:'Duke University',location:'Durham, NC',type:'Private Research'},
  {id:'northwestern',name:'Northwestern University',location:'Evanston, IL',type:'Private Research'},
  {id:'jhu',name:'Johns Hopkins University',location:'Baltimore, MD',type:'Private Research'},
  {id:'vanderbilt',name:'Vanderbilt University',location:'Nashville, TN',type:'Private Research'},
  {id:'rice',name:'Rice University',location:'Houston, TX',type:'Private Research'},
  {id:'notredame',name:'University of Notre Dame',location:'Notre Dame, IN',type:'Private · Catholic'},
  {id:'emory',name:'Emory University',location:'Atlanta, GA',type:'Private Research'},
  {id:'georgetown',name:'Georgetown University',location:'Washington, D.C.',type:'Private · Jesuit'},
  {id:'wustl',name:'Washington University in St. Louis',location:'St. Louis, MO',type:'Private Research'},
  {id:'carnegiemellon',name:'Carnegie Mellon University',location:'Pittsburgh, PA',type:'Private Research'},
  {id:'tufts',name:'Tufts University',location:'Medford, MA',type:'Private Research'},
  {id:'bc',name:'Boston College',location:'Chestnut Hill, MA',type:'Private · Jesuit'},
  {id:'bu',name:'Boston University',location:'Boston, MA',type:'Private Research'},
  {id:'usc',name:'University of Southern California',location:'Los Angeles, CA',type:'Private Research'},
  {id:'nyu',name:'New York University',location:'New York, NY',type:'Private Research'},
  {id:'tulane',name:'Tulane University',location:'New Orleans, LA',type:'Private Research'},
  {id:'wakef',name:'Wake Forest University',location:'Winston-Salem, NC',type:'Private Research'},
  {id:'lehigh',name:'Lehigh University',location:'Bethlehem, PA',type:'Private Research'},
  {id:'uofrochester',name:'University of Rochester',location:'Rochester, NY',type:'Private Research'},
  {id:'case',name:'Case Western Reserve University',location:'Cleveland, OH',type:'Private Research'},
  {id:'northeastern',name:'Northeastern University',location:'Boston, MA',type:'Private Research'},
  {id:'smu',name:'Southern Methodist University',location:'Dallas, TX',type:'Private Research'},
  {id:'fordham',name:'Fordham University',location:'New York, NY',type:'Private · Jesuit'},
  {id:'brandeis',name:'Brandeis University',location:'Waltham, MA',type:'Private Research'},
  {id:'american',name:'American University',location:'Washington, D.C.',type:'Private Research'},
  {id:'drexel',name:'Drexel University',location:'Philadelphia, PA',type:'Private Research'},
  {id:'villanova',name:'Villanova University',location:'Villanova, PA',type:'Private · Augustinian'},
  {id:'marquette',name:'Marquette University',location:'Milwaukee, WI',type:'Private · Jesuit'},
  {id:'loyolachi',name:'Loyola University Chicago',location:'Chicago, IL',type:'Private · Jesuit'},
  {id:'saintlouis',name:'Saint Louis University',location:'St. Louis, MO',type:'Private · Jesuit'},
  {id:'gonzaga',name:'Gonzaga University',location:'Spokane, WA',type:'Private · Jesuit'},
  {id:'santaclara',name:'Santa Clara University',location:'Santa Clara, CA',type:'Private · Jesuit'},
  // Liberal Arts Colleges
  {id:'williams',name:'Williams College',location:'Williamstown, MA',type:'Liberal Arts'},
  {id:'amherst',name:'Amherst College',location:'Amherst, MA',type:'Liberal Arts'},
  {id:'swarthmore',name:'Swarthmore College',location:'Swarthmore, PA',type:'Liberal Arts'},
  {id:'pomona',name:'Pomona College',location:'Claremont, CA',type:'Liberal Arts'},
  {id:'wellesley',name:'Wellesley College',location:'Wellesley, MA',type:"Liberal Arts · Women's"},
  {id:'bowdoin',name:'Bowdoin College',location:'Brunswick, ME',type:'Liberal Arts'},
  {id:'middlebury',name:'Middlebury College',location:'Middlebury, VT',type:'Liberal Arts'},
  {id:'carleton',name:'Carleton College',location:'Northfield, MN',type:'Liberal Arts'},
  {id:'grinnell',name:'Grinnell College',location:'Grinnell, IA',type:'Liberal Arts'},
  {id:'davidson',name:'Davidson College',location:'Davidson, NC',type:'Liberal Arts'},
  {id:'hamilton',name:'Hamilton College',location:'Clinton, NY',type:'Liberal Arts'},
  {id:'colgate',name:'Colgate University',location:'Hamilton, NY',type:'Liberal Arts'},
  {id:'colby',name:'Colby College',location:'Waterville, ME',type:'Liberal Arts'},
  {id:'bates',name:'Bates College',location:'Lewiston, ME',type:'Liberal Arts'},
  {id:'vassar',name:'Vassar College',location:'Poughkeepsie, NY',type:'Liberal Arts'},
  {id:'barnard',name:'Barnard College',location:'New York, NY',type:"Liberal Arts · Women's"},
  {id:'brynmawr',name:'Bryn Mawr College',location:'Bryn Mawr, PA',type:"Liberal Arts · Women's"},
  {id:'smith',name:'Smith College',location:'Northampton, MA',type:"Liberal Arts · Women's"},
  {id:'mount_holyoke',name:'Mount Holyoke College',location:'South Hadley, MA',type:"Liberal Arts · Women's"},
  {id:'oberlin',name:'Oberlin College',location:'Oberlin, OH',type:'Liberal Arts'},
  {id:'macalester',name:'Macalester College',location:'St. Paul, MN',type:'Liberal Arts'},
  {id:'kenyon',name:'Kenyon College',location:'Gambier, OH',type:'Liberal Arts'},
  {id:'denison',name:'Denison University',location:'Granville, OH',type:'Liberal Arts'},
  {id:'dickinson',name:'Dickinson College',location:'Carlisle, PA',type:'Liberal Arts'},
  {id:'gettysburg',name:'Gettysburg College',location:'Gettysburg, PA',type:'Liberal Arts'},
  {id:'lafayette',name:'Lafayette College',location:'Easton, PA',type:'Liberal Arts'},
  {id:'skidmore',name:'Skidmore College',location:'Saratoga Springs, NY',type:'Liberal Arts'},
  {id:'stlawrence',name:'St. Lawrence University',location:'Canton, NY',type:'Liberal Arts'},
  {id:'union',name:'Union College',location:'Schenectady, NY',type:'Liberal Arts'},
  {id:'connecticut',name:'Connecticut College',location:'New London, CT',type:'Liberal Arts'},
  {id:'trinity_ct',name:'Trinity College',location:'Hartford, CT',type:'Liberal Arts'},
  {id:'wesleyan',name:'Wesleyan University',location:'Middletown, CT',type:'Liberal Arts'},
  {id:'haverford',name:'Haverford College',location:'Haverford, PA',type:'Liberal Arts'},
  {id:'claremont_mc',name:'Claremont McKenna College',location:'Claremont, CA',type:'Liberal Arts'},
  {id:'harvey_mudd',name:'Harvey Mudd College',location:'Claremont, CA',type:'Liberal Arts · STEM'},
  {id:'scripps',name:'Scripps College',location:'Claremont, CA',type:"Liberal Arts · Women's"},
  {id:'pitzer',name:'Pitzer College',location:'Claremont, CA',type:'Liberal Arts'},
  {id:'colorado_col',name:'Colorado College',location:'Colorado Springs, CO',type:'Liberal Arts'},
  {id:'reed',name:'Reed College',location:'Portland, OR',type:'Liberal Arts'},
  {id:'whitman',name:'Whitman College',location:'Walla Walla, WA',type:'Liberal Arts'},
  {id:'furman',name:'Furman University',location:'Greenville, SC',type:'Liberal Arts'},
  {id:'rhodes',name:'Rhodes College',location:'Memphis, TN',type:'Liberal Arts'},
  {id:'sewanee',name:'Sewanee: The University of the South',location:'Sewanee, TN',type:'Liberal Arts'},
  {id:'wofford',name:'Wofford College',location:'Spartanburg, SC',type:'Liberal Arts'},
  {id:'centre',name:'Centre College',location:'Danville, KY',type:'Liberal Arts'},
  {id:'beloit',name:'Beloit College',location:'Beloit, WI',type:'Liberal Arts'},
  {id:'kalamazoo',name:'Kalamazoo College',location:'Kalamazoo, MI',type:'Liberal Arts'},
  {id:'stolaf',name:'St. Olaf College',location:'Northfield, MN',type:'Liberal Arts'},
  {id:'wooster',name:'College of Wooster',location:'Wooster, OH',type:'Liberal Arts'},
  {id:'allegheny',name:'Allegheny College',location:'Meadville, PA',type:'Liberal Arts'},
  {id:'oberlin2',name:'Ohio Wesleyan University',location:'Delaware, OH',type:'Liberal Arts'},
  {id:'earlham',name:'Earlham College',location:'Richmond, IN',type:'Liberal Arts · Quaker'},
  {id:'depauw',name:'DePauw University',location:'Greencastle, IN',type:'Liberal Arts'},
  {id:'wabash',name:'Wabash College',location:'Crawfordsville, IN',type:"Liberal Arts · Men's"},
  {id:'hanover',name:'Hanover College',location:'Hanover, IN',type:'Liberal Arts'},
  {id:'wheaton_il',name:'Wheaton College',location:'Wheaton, IL',type:'Liberal Arts · Evangelical'},
  {id:'knox',name:'Knox College',location:'Galesburg, IL',type:'Liberal Arts'},
  {id:'illinois_wesleyan',name:'Illinois Wesleyan University',location:'Bloomington, IL',type:'Liberal Arts'},
  {id:'augustana_il',name:'Augustana College',location:'Rock Island, IL',type:'Liberal Arts'},
  {id:'lewis_clark',name:'Lewis & Clark College',location:'Portland, OR',type:'Liberal Arts'},
  {id:'willamette',name:'Willamette University',location:'Salem, OR',type:'Liberal Arts'},
  {id:'pacific_lutheran',name:'Pacific Lutheran University',location:'Tacoma, WA',type:'Liberal Arts'},
  {id:'wheaton_ma',name:'Wheaton College',location:'Norton, MA',type:'Liberal Arts'},
  {id:'stmarys_md',name:"St. Mary's College of Maryland",location:"St. Mary's City, MD",type:'Public · Liberal Arts'},
  {id:'new_college',name:'New College of Florida',location:'Sarasota, FL',type:'Public · Liberal Arts'},
  {id:'eckerd',name:'Eckerd College',location:'St. Petersburg, FL',type:'Liberal Arts'},
  {id:'oxy',name:'Occidental College',location:'Los Angeles, CA',type:'Liberal Arts'},
  {id:'soka',name:'Soka University of America',location:'Aliso Viejo, CA',type:'Liberal Arts'},
  // Public Flagships
  {id:'umich',name:'University of Michigan',location:'Ann Arbor, MI',type:'Public Research'},
  {id:'unc',name:'UNC Chapel Hill',location:'Chapel Hill, NC',type:'Public Research'},
  {id:'virginia',name:'University of Virginia',location:'Charlottesville, VA',type:'Public Research'},
  {id:'ucla',name:'UCLA',location:'Los Angeles, CA',type:'Public Research'},
  {id:'ucberkeley',name:'UC Berkeley',location:'Berkeley, CA',type:'Public Research'},
  {id:'uw',name:'University of Washington',location:'Seattle, WA',type:'Public Research'},
  {id:'wisc',name:'University of Wisconsin-Madison',location:'Madison, WI',type:'Public Research'},
  {id:'illinois',name:'University of Illinois Urbana-Champaign',location:'Champaign, IL',type:'Public Research'},
  {id:'georgia',name:'University of Georgia',location:'Athens, GA',type:'Public Research'},
  {id:'ohio_state',name:'Ohio State University',location:'Columbus, OH',type:'Public Research'},
  {id:'penn_state',name:'Penn State University',location:'University Park, PA',type:'Public Research'},
  {id:'purdue',name:'Purdue University',location:'West Lafayette, IN',type:'Public Research'},
  {id:'indiana',name:'Indiana University',location:'Bloomington, IN',type:'Public Research'},
  {id:'minnesota',name:'University of Minnesota',location:'Minneapolis, MN',type:'Public Research'},
  {id:'iowa',name:'University of Iowa',location:'Iowa City, IA',type:'Public Research'},
  {id:'michigan_state',name:'Michigan State University',location:'East Lansing, MI',type:'Public Research'},
  {id:'rutgers',name:'Rutgers University',location:'New Brunswick, NJ',type:'Public Research'},
  {id:'maryland',name:'University of Maryland',location:'College Park, MD',type:'Public Research'},
  {id:'pitt',name:'University of Pittsburgh',location:'Pittsburgh, PA',type:'Public Research'},
  {id:'florida',name:'University of Florida',location:'Gainesville, FL',type:'Public Research'},
  {id:'fsu',name:'Florida State University',location:'Tallahassee, FL',type:'Public Research'},
  {id:'texas',name:'University of Texas at Austin',location:'Austin, TX',type:'Public Research'},
  {id:'tamu',name:'Texas A&M University',location:'College Station, TX',type:'Public Research'},
  {id:'colorado_boulder',name:'University of Colorado Boulder',location:'Boulder, CO',type:'Public Research'},
  {id:'arizona',name:'University of Arizona',location:'Tucson, AZ',type:'Public Research'},
  {id:'arizona_state',name:'Arizona State University',location:'Tempe, AZ',type:'Public Research'},
  {id:'ucdavis',name:'UC Davis',location:'Davis, CA',type:'Public Research'},
  {id:'ucsandiego',name:'UC San Diego',location:'La Jolla, CA',type:'Public Research'},
  {id:'ucsb',name:'UC Santa Barbara',location:'Santa Barbara, CA',type:'Public Research'},
  {id:'ucirvine',name:'UC Irvine',location:'Irvine, CA',type:'Public Research'},
  {id:'vtech',name:'Virginia Tech',location:'Blacksburg, VA',type:'Public Research'},
  {id:'william_mary',name:'College of William & Mary',location:'Williamsburg, VA',type:'Public Research'},
  {id:'ga_tech',name:'Georgia Tech',location:'Atlanta, GA',type:'Public Research'},
  {id:'auburn',name:'Auburn University',location:'Auburn, AL',type:'Public Research'},
  {id:'alabama',name:'University of Alabama',location:'Tuscaloosa, AL',type:'Public Research'},
  {id:'lsu',name:'Louisiana State University',location:'Baton Rouge, LA',type:'Public Research'},
  {id:'tennessee',name:'University of Tennessee',location:'Knoxville, TN',type:'Public Research'},
  {id:'kentucky',name:'University of Kentucky',location:'Lexington, KY',type:'Public Research'},
  {id:'scar',name:'University of South Carolina',location:'Columbia, SC',type:'Public Research'},
  {id:'clemson',name:'Clemson University',location:'Clemson, SC',type:'Public Research'},
  {id:'ncstate',name:'NC State University',location:'Raleigh, NC',type:'Public Research'},
  {id:'missouri',name:'University of Missouri',location:'Columbia, MO',type:'Public Research'},
  {id:'kansas',name:'University of Kansas',location:'Lawrence, KS',type:'Public Research'},
  {id:'nebraska',name:'University of Nebraska',location:'Lincoln, NE',type:'Public Research'},
  {id:'iowa_state',name:'Iowa State University',location:'Ames, IA',type:'Public Research'},
  {id:'oklahoma',name:'University of Oklahoma',location:'Norman, OK',type:'Public Research'},
  {id:'utah',name:'University of Utah',location:'Salt Lake City, UT',type:'Public Research'},
  {id:'oregon',name:'University of Oregon',location:'Eugene, OR',type:'Public Research'},
  {id:'oregon_state',name:'Oregon State University',location:'Corvallis, OR',type:'Public Research'},
  {id:'colorado_state',name:'Colorado State University',location:'Fort Collins, CO',type:'Public Research'},
  {id:'vermont',name:'University of Vermont',location:'Burlington, VT',type:'Public Research'},
  {id:'umass',name:'UMass Amherst',location:'Amherst, MA',type:'Public Research'},
  {id:'uconn',name:'University of Connecticut',location:'Storrs, CT',type:'Public Research'},
  {id:'uri',name:'University of Rhode Island',location:'Kingston, RI',type:'Public Research'},
  {id:'delaware',name:'University of Delaware',location:'Newark, DE',type:'Public Research'},
  {id:'stony_brook',name:'Stony Brook University',location:'Stony Brook, NY',type:'Public Research'},
  {id:'suny_buffalo',name:'SUNY Buffalo',location:'Buffalo, NY',type:'Public Research'},
  {id:'suny_albany',name:'SUNY Albany',location:'Albany, NY',type:'Public Research'},
  {id:'suny_binghamton',name:'Binghamton University',location:'Binghamton, NY',type:'Public Research'},
  {id:'ucf',name:'University of Central Florida',location:'Orlando, FL',type:'Public Research'},
  {id:'usf',name:'University of South Florida',location:'Tampa, FL',type:'Public Research'},
  {id:'fiu',name:'Florida International University',location:'Miami, FL',type:'Public Research'},
  {id:'wsu',name:'Washington State University',location:'Pullman, WA',type:'Public Research'},
  {id:'idaho',name:'University of Idaho',location:'Moscow, ID',type:'Public Research'},
  {id:'hawaii',name:'University of Hawaii at Manoa',location:'Honolulu, HI',type:'Public Research'},
  // Military Academies
  {id:'westpoint',name:'West Point (USMA)',location:'West Point, NY',type:'Military Academy'},
  {id:'annapolis',name:'US Naval Academy',location:'Annapolis, MD',type:'Military Academy'},
  {id:'airforce',name:'US Air Force Academy',location:'Colorado Springs, CO',type:'Military Academy'},
  {id:'coastguard',name:'US Coast Guard Academy',location:'New London, CT',type:'Military Academy'},
  {id:'citadel',name:'The Citadel',location:'Charleston, SC',type:'Military College'},
  {id:'vmi',name:'Virginia Military Institute',location:'Lexington, VA',type:'Military College'},
  // Tech Schools
  {id:'rpi',name:'Rensselaer Polytechnic Institute',location:'Troy, NY',type:'Private · Tech'},
  {id:'wpi',name:'Worcester Polytechnic Institute',location:'Worcester, MA',type:'Private · Tech'},
  {id:'rose_hulman',name:'Rose-Hulman Institute of Technology',location:'Terre Haute, IN',type:'Private · Tech'},
  {id:'mines',name:'Colorado School of Mines',location:'Golden, CO',type:'Public · Tech'},
  {id:'stevens',name:'Stevens Institute of Technology',location:'Hoboken, NJ',type:'Private · Tech'},
  {id:'njit',name:'NJIT',location:'Newark, NJ',type:'Public · Tech'},
  // HBCUs
  {id:'howard',name:'Howard University',location:'Washington, D.C.',type:'HBCU'},
  {id:'spelman',name:'Spelman College',location:'Atlanta, GA',type:"HBCU · Women's"},
  {id:'morehouse',name:'Morehouse College',location:'Atlanta, GA',type:'HBCU'},
  {id:'fisk',name:'Fisk University',location:'Nashville, TN',type:'HBCU'},
  {id:'hampton',name:'Hampton University',location:'Hampton, VA',type:'HBCU'},
  {id:'tuskegee',name:'Tuskegee University',location:'Tuskegee, AL',type:'HBCU'},
  // Additional private universities
  {id:'syracuse',name:'Syracuse University',location:'Syracuse, NY',type:'Private Research'},
  {id:'gw',name:'George Washington University',location:'Washington, D.C.',type:'Private Research'},
  {id:'pepperdine',name:'Pepperdine University',location:'Malibu, CA',type:'Private Research'},
  {id:'baylor',name:'Baylor University',location:'Waco, TX',type:'Private Research'},
  {id:'tcu',name:'TCU',location:'Fort Worth, TX',type:'Private Research'},
  {id:'miami_fl',name:'University of Miami',location:'Coral Gables, FL',type:'Private Research'},
  {id:'rollins',name:'Rollins College',location:'Winter Park, FL',type:'Private'},
  {id:'stetson',name:'Stetson University',location:'DeLand, FL',type:'Private'},
  {id:'elon',name:'Elon University',location:'Elon, NC',type:'Private'},
  {id:'high_point',name:'High Point University',location:'High Point, NC',type:'Private'},
  {id:'cofc',name:'College of Charleston',location:'Charleston, SC',type:'Public'},
  {id:'mercer',name:'Mercer University',location:'Macon, GA',type:'Private'},
  {id:'berry',name:'Berry College',location:'Mount Berry, GA',type:'Private'},
  {id:'butler',name:'Butler University',location:'Indianapolis, IN',type:'Private'},
  {id:'xavier_oh',name:'Xavier University',location:'Cincinnati, OH',type:'Private · Jesuit'},
  {id:'dayton',name:'University of Dayton',location:'Dayton, OH',type:'Private · Marianist'},
  {id:'john_carroll',name:'John Carroll University',location:'University Heights, OH',type:'Private · Jesuit'},
  {id:'miami_oh',name:'Miami University',location:'Oxford, OH',type:'Public'},
  {id:'ohio',name:'Ohio University',location:'Athens, OH',type:'Public'},
  {id:'ohio_u',name:'Ohio University',location:'Athens, OH',type:'Public'},
  {id:'bradley',name:'Bradley University',location:'Peoria, IL',type:'Private'},
  {id:'loyola_chicago',name:'Loyola University Chicago',location:'Chicago, IL',type:'Private · Jesuit'},
  {id:'depaul',name:'DePaul University',location:'Chicago, IL',type:'Private · Vincentian'},
  {id:'ball_state',name:'Ball State University',location:'Muncie, IN',type:'Public'},
  {id:'valparaiso',name:'Valparaiso University',location:'Valparaiso, IN',type:'Private'},
  {id:'seton_hall',name:'Seton Hall University',location:'South Orange, NJ',type:'Private · Catholic'},
  {id:'villanova2',name:'Villanova University',location:'Villanova, PA',type:'Private · Augustinian'},
  {id:'tcnj',name:'The College of New Jersey',location:'Ewing, NJ',type:'Public'},
  {id:'rowan',name:'Rowan University',location:'Glassboro, NJ',type:'Public'},
  {id:'quinnipiac',name:'Quinnipiac University',location:'Hamden, CT',type:'Private'},
  {id:'fairfield',name:'Fairfield University',location:'Fairfield, CT',type:'Private · Jesuit'},
  {id:'providence',name:'Providence College',location:'Providence, RI',type:'Private · Dominican'},
  {id:'bentley',name:'Bentley University',location:'Waltham, MA',type:'Private'},
  {id:'babson',name:'Babson College',location:'Wellesley, MA',type:'Private · Business'},
  {id:'northeastern2',name:'Northeastern University',location:'Boston, MA',type:'Private Research'},
  {id:'suffolk',name:'Suffolk University',location:'Boston, MA',type:'Private'},
  {id:'simmons',name:'Simmons University',location:'Boston, MA',type:'Private'},
  {id:'umass_lowell',name:'UMass Lowell',location:'Lowell, MA',type:'Public'},
  {id:'umass_boston',name:'UMass Boston',location:'Boston, MA',type:'Public'},
  {id:'bridgewater',name:'Bridgewater State University',location:'Bridgewater, MA',type:'Public'},
  {id:'suny_geneseo',name:'SUNY Geneseo',location:'Geneseo, NY',type:'Public'},
  {id:'suny_purchase',name:'SUNY Purchase',location:'Purchase, NY',type:'Public'},
  {id:'suny_oswego',name:'SUNY Oswego',location:'Oswego, NY',type:'Public'},
  {id:'iona',name:'Iona University',location:'New Rochelle, NY',type:'Private · Lasallian'},
  {id:'manhattan',name:'Manhattan College',location:'Bronx, NY',type:'Private · Lasallian'},
  {id:'siena',name:'Siena College',location:'Loudonville, NY',type:'Private · Franciscan'},
  {id:'lemoyne',name:'Le Moyne College',location:'Syracuse, NY',type:'Private · Jesuit'},
  {id:'canisius',name:'Canisius University',location:'Buffalo, NY',type:'Private · Jesuit'},
  {id:'hofstra',name:'Hofstra University',location:'Hempstead, NY',type:'Private'},
  {id:'adelphi',name:'Adelphi University',location:'Garden City, NY',type:'Private'},
  {id:'pace',name:'Pace University',location:'New York, NY',type:'Private'},
  {id:'fordham2',name:'Fordham University',location:'New York, NY',type:'Private · Jesuit'},
  {id:'loyolamarymount',name:'Loyola Marymount University',location:'Los Angeles, CA',type:'Private · Jesuit'},
  {id:'uofsandiego',name:'University of San Diego',location:'San Diego, CA',type:'Private · Catholic'},
  {id:'seattle_u',name:'Seattle University',location:'Seattle, WA',type:'Private · Jesuit'},
  {id:'portland',name:'University of Portland',location:'Portland, OR',type:'Private · Holy Cross'},
  {id:'pacific',name:'University of the Pacific',location:'Stockton, CA',type:'Private'},
  {id:'byu',name:'Brigham Young University',location:'Provo, UT',type:'Private · LDS'},
  {id:'sdsu',name:'San Diego State University',location:'San Diego, CA',type:'Public'},
  {id:'sjsu',name:'San Jose State University',location:'San Jose, CA',type:'Public'},
  {id:'cal_poly_slo',name:'Cal Poly San Luis Obispo',location:'San Luis Obispo, CA',type:'Public'},
  {id:'csulb',name:'Cal State Long Beach',location:'Long Beach, CA',type:'Public'},
  {id:'sfstate',name:'San Francisco State University',location:'San Francisco, CA',type:'Public'},
  {id:'ttu',name:'Texas Tech University',location:'Lubbock, TX',type:'Public Research'},
  {id:'uh',name:'University of Houston',location:'Houston, TX',type:'Public Research'},
  {id:'appalachian',name:'Appalachian State University',location:'Boone, NC',type:'Public'},
  {id:'ecu',name:'East Carolina University',location:'Greenville, NC',type:'Public'},
  {id:'uncc',name:'UNC Charlotte',location:'Charlotte, NC',type:'Public'},
  {id:'coastal_carolina',name:'Coastal Carolina University',location:'Conway, SC',type:'Public'},
  {id:'bellarmine',name:'Bellarmine University',location:'Louisville, KY',type:'Private · Catholic'},
  {id:'transylvania',name:'Transylvania University',location:'Lexington, KY',type:'Private'},
  {id:'berea',name:'Berea College',location:'Berea, KY',type:'Private'},
  {id:'hillsdale',name:'Hillsdale College',location:'Hillsdale, MI',type:'Private'},
  {id:'hope',name:'Hope College',location:'Holland, MI',type:'Liberal Arts'},
  {id:'kzoo',name:'Kalamazoo College',location:'Kalamazoo, MI',type:'Liberal Arts'},
  {id:'albion',name:'Albion College',location:'Albion, MI',type:'Liberal Arts'},
  {id:'agnes_scott',name:'Agnes Scott College',location:'Decatur, GA',type:"Private · Women's"},
  {id:'spelman2',name:'Spelman College',location:'Atlanta, GA',type:'HBCU'},
  {id:'minerva',name:'Minerva University',location:'San Francisco, CA',type:'Private'},
  {id:'wwu',name:'Western Washington University',location:'Bellingham, WA',type:'Public'},
  {id:'ewu',name:'Eastern Washington University',location:'Cheney, WA',type:'Public'},
  {id:'southern_oregon',name:'Southern Oregon University',location:'Ashland, OR',type:'Public'},
  {id:'nova_southeastern',name:'Nova Southeastern University',location:'Fort Lauderdale, FL',type:'Private'},
  {id:'jacksonville',name:'Jacksonville University',location:'Jacksonville, FL',type:'Private'},
  {id:'fau',name:'Florida Atlantic University',location:'Boca Raton, FL',type:'Public'},
  {id:'hartford',name:'University of Hartford',location:'West Hartford, CT',type:'Private'},
  {id:'sacred_heart',name:'Sacred Heart University',location:'Fairfield, CT',type:'Private'},
  {id:'roger_williams',name:'Roger Williams University',location:'Bristol, RI',type:'Private'},
  {id:'salve_regina',name:'Salve Regina University',location:'Newport, RI',type:'Private'},
  {id:'stonehill',name:'Stonehill College',location:'Easton, MA',type:'Private'},
  {id:'merrimack',name:'Merrimack College',location:'North Andover, MA',type:'Private'},
  {id:'assumption',name:'Assumption University',location:'Worcester, MA',type:'Private'},
  {id:'gordon',name:'Gordon College',location:'Wenham, MA',type:'Private · Christian'},
  {id:'mass_maritime',name:'Massachusetts Maritime Academy',location:'Buzzards Bay, MA',type:'Public · Maritime'},
];
